# This file was generated by GoReleaser. DO NOT EDIT.
cask "unigo" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "8935477e5d729dc4b173bf731cdf41d0a44598e444040df0186cb7667587d1c2"
      url "https://github.com/snowdreamtech/unigo/releases/download/v#{version}/unigo_Darwin_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unigo_Darwin_x86_64/unigo", "unigo"
    end
    on_arm do
      sha256 "c294efa88a71dd966f399f060a69aad1319420826720d6d8490aa72325ab40e6"
      url "https://github.com/snowdreamtech/unigo/releases/download/v#{version}/unigo_Darwin_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unigo_Darwin_arm64/unigo", "unigo"
    end
  end

  on_linux do
    on_intel do
      sha256 "8761623ca1c4345e5ececaaa6ae5602210ecb3aa1f9c5c933aec1114f5be2556"
      url "https://github.com/snowdreamtech/unigo/releases/download/v#{version}/unigo_Linux_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unigo_Linux_x86_64/unigo", "unigo"
    end
    on_arm do
      sha256 "c07450166c3353a073903e05f85a7ecd7196558f7e289a7cd67a1cdfd96891c5"
      url "https://github.com/snowdreamtech/unigo/releases/download/v#{version}/unigo_Linux_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unigo_Linux_arm64/unigo", "unigo"
    end
  end

  name "unigo"
  desc "Snowdream Tech AI IDE Template is an enterprise-grade, foundational template designed for multi-AI IDE collaboration."
  homepage "https://github.com/snowdreamtech/unigo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unigo"
  manpage "manpages/unigo.1"
  bash_completion "completions/unigo.bash"
  fish_completion "completions/unigo.fish"
  zsh_completion "completions/unigo.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unigo"]
    end
  end

  # No zap stanza required

end
