# This file was generated by GoReleaser. DO NOT EDIT.
cask "unigo" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "52cf3beb25892973aa596cb6aae8187f063608b6888e41774c0915eac1353195"
      url "https://github.com/snowdreamtech/unigo/releases/download/v#{version}/unigo_Darwin_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unigo_Darwin_x86_64/unigo", "unigo"
    end
    on_arm do
      sha256 "0f6af3e5dcb6aee5ac827e41240c619640ba4694ee077e41a2427939af0cfc9a"
      url "https://github.com/snowdreamtech/unigo/releases/download/v#{version}/unigo_Darwin_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unigo_Darwin_arm64/unigo", "unigo"
    end
  end

  on_linux do
    on_intel do
      sha256 "b3e14df745b025be940013b827472b6eb17562cb22a019977e40a02bebd0d29b"
      url "https://github.com/snowdreamtech/unigo/releases/download/v#{version}/unigo_Linux_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unigo_Linux_x86_64/unigo", "unigo"
    end
    on_arm do
      sha256 "6d4c921278f6f9c3cf7859d9d60aa96611be166173a92897b9967a647cc48224"
      url "https://github.com/snowdreamtech/unigo/releases/download/v#{version}/unigo_Linux_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unigo_Linux_arm64/unigo", "unigo"
    end
  end

  name "unigo"
  desc "Snowdream Tech AI IDE Template is an enterprise-grade, foundational template designed for multi-AI IDE collaboration."
  homepage "https://github.com/snowdreamtech/unigo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unigo"
  manpage "manpages/unigo.1"
  bash_completion "completions/unigo.bash"
  fish_completion "completions/unigo.fish"
  zsh_completion "completions/unigo.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unigo"]
    end
  end

  # No zap stanza required

end
