# This file was generated by GoReleaser. DO NOT EDIT.
cask "unigo" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "be4ee7b5d512031cee77225ace58e055a25f8638f35bf6fb702c0cad0cd23f3f"
      url "https://github.com/snowdreamtech/unigo/releases/download/v#{version}/unigo_Darwin_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unigo_Darwin_x86_64/unigo", "unigo"
    end
    on_arm do
      sha256 "24eabc223e0b62ad58f946c62af28be70b886805776c58323e021bfc60391d2c"
      url "https://github.com/snowdreamtech/unigo/releases/download/v#{version}/unigo_Darwin_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unigo_Darwin_arm64/unigo", "unigo"
    end
  end

  on_linux do
    on_intel do
      sha256 "ade69bcd3b80dfa4bb2f40eaff7feb89e8909a21f0a0485a9bd86556958bb698"
      url "https://github.com/snowdreamtech/unigo/releases/download/v#{version}/unigo_Linux_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unigo_Linux_x86_64/unigo", "unigo"
    end
    on_arm do
      sha256 "25e717dceb1ebacf2e76c44aeef3d488e19f9f4316f44627cb3ee19261f97ff5"
      url "https://github.com/snowdreamtech/unigo/releases/download/v#{version}/unigo_Linux_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unigo_Linux_arm64/unigo", "unigo"
    end
  end

  name "unigo"
  desc "Snowdream Tech AI IDE Template is an enterprise-grade, foundational template designed for multi-AI IDE collaboration."
  homepage "https://github.com/snowdreamtech/unigo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unigo"
  manpage "manpages/unigo.1"
  bash_completion "completions/unigo.bash"
  fish_completion "completions/unigo.fish"
  zsh_completion "completions/unigo.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unigo"]
    end
  end

  # No zap stanza required

end
