# This file was generated by GoReleaser. DO NOT EDIT.
cask "unirtm" do
  version "0.23.1"

  on_macos do
    on_intel do
      sha256 "2614f860622be0e36b0db9112aa16600f76afb06df05b48d86565a28b4928ee7"
      url "https://github.com/snowdreamtech/UniRTM/releases/download/v#{version}/unirtm_Darwin_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unirtm_Darwin_x86_64/unirtm", "unirtm"
    end
    on_arm do
      sha256 "831b1f0adca0140c917615836ca8f52d283c6dba422237ba5826134bfa1ba8ee"
      url "https://github.com/snowdreamtech/UniRTM/releases/download/v#{version}/unirtm_Darwin_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unirtm_Darwin_arm64/unirtm", "unirtm"
    end
  end

  on_linux do
    on_intel do
      sha256 "b647485cdace1f3a3de922ba3fc234c05584c59043bf9193ad44b8606f2e3a2b"
      url "https://github.com/snowdreamtech/UniRTM/releases/download/v#{version}/unirtm_Linux_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unirtm_Linux_x86_64/unirtm", "unirtm"
    end
    on_arm do
      sha256 "ffadf0635880d870baa7cc4ec629e21304c75421d473e9451fad402f1ce240a0"
      url "https://github.com/snowdreamtech/UniRTM/releases/download/v#{version}/unirtm_Linux_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unirtm_Linux_arm64/unirtm", "unirtm"
    end
  end

  name "unirtm"
  desc "UniRTM (Uni Runtime and Tools Manager) is a cross-platform developer toolchain manager."
  homepage "https://github.com/snowdreamtech/UniRTM"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unirtm"
  manpage "manpages/unirtm.1"
  bash_completion "completions/unirtm.bash"
  fish_completion "completions/unirtm.fish"
  zsh_completion "completions/unirtm.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unirtm"]
    end
  end

  # No zap stanza required

end
