# This file was generated by GoReleaser. DO NOT EDIT.
cask "unirtm" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "b5194707e5f7357d9c6ffc95fed9ce58a0cc2f8af6c9d2de44ba5054480f9bb8"
      url "https://github.com/snowdreamtech/UniRTM/releases/download/v#{version}/unirtm_Darwin_x86_64.tar.gz"
      rename "unirtm_Darwin_x86_64/unirtm", "unirtm"
    end
    on_arm do
      sha256 "eaaea9258830a71eb833033efd30441e393e907f166a2ec1e25e442071b6c35c"
      url "https://github.com/snowdreamtech/UniRTM/releases/download/v#{version}/unirtm_Darwin_arm64.tar.gz"
      rename "unirtm_Darwin_arm64/unirtm", "unirtm"
    end
  end

  name "unirtm"
  desc "UniRTM (Uni Runtime and Tools Manager) is a cross-platform developer toolchain manager."
  homepage "https://github.com/snowdreamtech/UniRTM"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unirtm"
  manpage "manpages/unirtm.1"
  bash_completion "completions/unirtm.bash"
  fish_completion "completions/unirtm.fish"
  zsh_completion "completions/unirtm.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unirtm"]
    end
  end

  # No zap stanza required

end
