# This file was generated by GoReleaser. DO NOT EDIT.
cask "unirtm" do
  version "0.28.0"

  on_macos do
    on_intel do
      sha256 "901ec23e1f92487a4f86bb16a48db83607ab99622c1cea4b7ae96d20579aca94"
      url "https://github.com/snowdreamtech/UniRTM/releases/download/v#{version}/unirtm_Darwin_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unirtm_Darwin_x86_64/unirtm", "unirtm"
    end
    on_arm do
      sha256 "0365f012300814a5d2d7965c39cca8af81c2439c9ffe96c4dc9733062c84d0b5"
      url "https://github.com/snowdreamtech/UniRTM/releases/download/v#{version}/unirtm_Darwin_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unirtm_Darwin_arm64/unirtm", "unirtm"
    end
  end

  on_linux do
    on_intel do
      sha256 "25c4ceba93157b864b6327279fce79ae0fc1714c197fdb31cda574cd47d7fb3e"
      url "https://github.com/snowdreamtech/UniRTM/releases/download/v#{version}/unirtm_Linux_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unirtm_Linux_x86_64/unirtm", "unirtm"
    end
    on_arm do
      sha256 "fd6360e0328877fc61251203c09b162f04ab8e06e51e7092ce671bcf9e79023c"
      url "https://github.com/snowdreamtech/UniRTM/releases/download/v#{version}/unirtm_Linux_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unirtm_Linux_arm64/unirtm", "unirtm"
    end
  end

  name "unirtm"
  desc "UniRTM (Uni Runtime and Tools Manager) is a cross-platform developer toolchain manager."
  homepage "https://github.com/snowdreamtech/UniRTM"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unirtm"
  manpage "manpages/unirtm.1"
  bash_completion "completions/unirtm.bash"
  fish_completion "completions/unirtm.fish"
  zsh_completion "completions/unirtm.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unirtm"]
    end
  end

  # No zap stanza required

end
