# This file was generated by GoReleaser. DO NOT EDIT.
cask "unistack" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "17ecb74509f0798ea1601c620b404c18748876f2ebc726741079f74312f28a1f"
      url "https://github.com/snowdreamtech/unistack/releases/download/v#{version}/unistack_Darwin_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unistack_Darwin_x86_64/unistack", "unistack"
    end
    on_arm do
      sha256 "147d39f4a8c0775a0f9a4dd17bc2f24ece70c7255a9da54979a7919582860a18"
      url "https://github.com/snowdreamtech/unistack/releases/download/v#{version}/unistack_Darwin_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unistack_Darwin_arm64/unistack", "unistack"
    end
  end

  on_linux do
    on_intel do
      sha256 "27a812b221453370a958fa5ce08f9adefe452004d65a5bb0be45b8a17c88adb8"
      url "https://github.com/snowdreamtech/unistack/releases/download/v#{version}/unistack_Linux_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unistack_Linux_x86_64/unistack", "unistack"
    end
    on_arm do
      sha256 "cf33593d6504331cc564d32d20dfeec9c90bb1830a07cadcbe5cb5a5012625aa"
      url "https://github.com/snowdreamtech/unistack/releases/download/v#{version}/unistack_Linux_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unistack_Linux_arm64/unistack", "unistack"
    end
  end

  name "unistack"
  desc "Snowdream Tech AI IDE Template is an enterprise-grade, foundational template designed for multi-AI IDE collaboration."
  homepage "https://github.com/snowdreamtech/unistack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unistack"
  manpage "manpages/unistack.1"
  bash_completion "completions/unistack.bash"
  fish_completion "completions/unistack.fish"
  zsh_completion "completions/unistack.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unistack"]
    end
  end

  # No zap stanza required

end
