# This file was generated by GoReleaser. DO NOT EDIT.
cask "unistack" do
  version "0.0.10"

  on_macos do
    on_intel do
      sha256 "65274f2a12a81b02908e98c0a1489febc72f45d401b04a9c31a30a3d4b3b3d72"
      url "https://github.com/snowdreamtech/unistack/releases/download/v#{version}/unistack_Darwin_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unistack_Darwin_x86_64/unistack", "unistack"
    end
    on_arm do
      sha256 "a23d8f883347aa6ec8c5b67d4baf4702f90bef54ee7380b0a6ba4efe6a0da58e"
      url "https://github.com/snowdreamtech/unistack/releases/download/v#{version}/unistack_Darwin_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unistack_Darwin_arm64/unistack", "unistack"
    end
  end

  on_linux do
    on_intel do
      sha256 "d28f9803a8fa5983f678c06c4bf645c476767c3c80084a03b5992b1dee4ab7a1"
      url "https://github.com/snowdreamtech/unistack/releases/download/v#{version}/unistack_Linux_x86_64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unistack_Linux_x86_64/unistack", "unistack"
    end
    on_arm do
      sha256 "897ea92dc068934c60868754699b28af846dd1099ff59c3cf542aa320fa8dd0a"
      url "https://github.com/snowdreamtech/unistack/releases/download/v#{version}/unistack_Linux_arm64.tar.gz",
        verified: "github.com/snowdreamtech/"
      rename "unistack_Linux_arm64/unistack", "unistack"
    end
  end

  name "unistack"
  desc "Snowdream Tech AI IDE Template is an enterprise-grade, foundational template designed for multi-AI IDE collaboration."
  homepage "https://github.com/snowdreamtech/unistack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unistack"
  manpage "manpages/unistack.1"
  bash_completion "completions/unistack.bash"
  fish_completion "completions/unistack.fish"
  zsh_completion "completions/unistack.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unistack"]
    end
  end

  # No zap stanza required

end
