# This file was generated by GoReleaser. DO NOT EDIT.
cask "unistack" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "817ffe51a60ffda419111377b2423b3d1fa02c703f3d87fa79256ca6c31e4500"
      url "https://github.com/snowdreamtech/unistack/releases/download/v#{version}/unistack_Darwin_arm64.tar.gz"
      rename "unistack_Darwin_arm64/unistack", "unistack"
    end
    on_intel do
      sha256 "33de526d1f22dc8c52527f970d8a3bc561a572174e7326a461f58276a452ef91"
      url "https://github.com/snowdreamtech/unistack/releases/download/v#{version}/unistack_Darwin_x86_64.tar.gz"
      rename "unistack_Darwin_x86_64/unistack", "unistack"
    end
  end
  on_linux do
    on_arm do
      sha256 "a19e22220b91400ee982fd04a15016257fbf9d33dba9867a7d39dbe1d5863cbc"
      url "https://github.com/snowdreamtech/unistack/releases/download/v#{version}/unistack_Linux_arm64.tar.gz"
      rename "unistack_Linux_arm64/unistack", "unistack"
    end
    on_intel do
      sha256 "ccb80ce29aa132ecedf8728d1b2d4328336b03c08fbee7a00c775d3629d6fd39"
      url "https://github.com/snowdreamtech/unistack/releases/download/v#{version}/unistack_Linux_x86_64.tar.gz"
      rename "unistack_Linux_x86_64/unistack", "unistack"
    end
  end

  name "unistack"
  desc "Snowdream Tech AI IDE Template is an enterprise-grade, foundational template designed for multi-AI IDE collaboration."
  homepage "https://github.com/snowdreamtech/unistack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unistack"
  manpage "manpages/unistack.1"
  bash_completion "completions/unistack.bash"
  fish_completion "completions/unistack.fish"
  zsh_completion "completions/unistack.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unistack"]
    end
  end

  # No zap stanza required
end
